apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neath-tan7026-pipejet-ui-branch-dev-latest-ingress
  namespace: neath-tan7026-pipejet-ui-branch-dev-latest
  annotation:
spec:
  ingressClassName: nginx
  rules:
  - host: pipejet.pipejet.site
    http:
      paths:
      - path: /
        pathType: Prefix  
        backend:
          service:
            name: neath-tan7026-pipejet-ui-branch-dev-latest-service 
            port:
              number: 8227
